local_costmap:
   global_frame: /map
   robot_base_frame: /base_link
   update_frequency: 3.0
   publish_frequency: 1.0
   static_map: true
   rolling_window: true
   width: 1.0
   height: 1.0
   resolution: 0.01
   transform_tolerance: 1.0
   map_type: costmap
